### ISSUE TITLE
Unable to deploy. Getting Status Code: 400; Error Code: ValidationError

### ISSUE THREAD

**Issue by thanarathanaml** [lumigo-io/SAR-Lambda-Janitor#55]
When I trying to deploy this cloud formation application in our organisation aws account from the region us-east-2. I am getting  validation error when I click Deploy button.
<img width="1356" alt="Screenshot 2023-04-12 at 10 58 31 AM" src="https://user-images.githubusercontent.com/71483191/231359744-ff4a6393-2456-43a0-9281-d9c4e99ad49e.png">

**Comment by theburningmonk** [comment]
Looks like the issue was that you had a failed deployment before, and once a stack is in that ROLLBACK_COMPLETE state you can't update it.

So the fix is to go to CloudFormation in us-east-2, find the stack called serverlessrepo-lambda-janitor, delete it, and then try again.

**Comment by theburningmonk** [comment]
Closing for now, feel free to reopen if you still can't get it to work
